services:
  - type: web
    name: ballvision-ai
    runtime: python

    envVars:
      - key: PYTHON_VERSION
        value: 3.12.4

    buildCommand: pip install -r requirements.txt

    startCommand: streamlit run app.py --server.port=$PORT --server.address=0.0.0.0
