FLAG_FILES = {
    "Afghanistan": "af.svg",
    "Albania": "al.svg",
    "Algeria": "dz.svg",
    "Andorra": "ad.svg",
    "Argentina": "ar.svg",
    "Armenia": "am.svg",
    "Australia": "au.svg",
    "Austria": "at.svg",
    "Azerbaijan": "az.svg",
    "Bangladesh": "bd.svg",
    "Belarus": "by.svg",
    "Belgium": "be.svg",
    "Bolivia": "bo.svg",
    "Bosnia and Herzegovina": "ba.svg",
    "Brazil": "br.svg",
    "Bulgaria": "bg.svg",
    "Cameroon": "cm.svg",
    "Canada": "ca.svg",
    "Chile": "cl.svg",
    "China PR": "cn.svg",
    "Colombia": "co.svg",
    "Costa Rica": "cr.svg",
    "Croatia": "hr.svg",
    "Czechia": "cz.svg",
    "Denmark": "dk.svg",
    "Ecuador": "ec.svg",
    "Egypt": "eg.svg",
    "England": "gb-eng.svg",
    "Finland": "fi.svg",
    "France": "fr.svg",
    "Germany": "de.svg",
    "Ghana": "gh.svg",
    "Greece": "gr.svg",
    "Hungary": "hu.svg",
    "India": "in.svg",
    "Iran": "ir.svg",
    "Iraq": "iq.svg",
    "Ireland": "ie.svg",
    "Israel": "il.svg",
    "Italy": "it.svg",
    "Ivory Coast": "ci.svg",
    "Japan": "jp.svg",
    "Mexico": "mx.svg",
    "Morocco": "ma.svg",
    "Netherlands": "nl.svg",
    "New Zealand": "nz.svg",
    "Nigeria": "ng.svg",
    "Norway": "no.svg",
    "Panama": "pa.svg",
    "Paraguay": "py.svg",
    "Poland": "pl.svg",
    "Portugal": "pt.svg",
    "Qatar": "qa.svg",
    "Romania": "ro.svg",
    "Saudi Arabia": "sa.svg",
    "Scotland": "gb-sct.svg",
    "Senegal": "sn.svg",
    "Serbia": "rs.svg",
    "Slovakia": "sk.svg",
    "Slovenia": "si.svg",
    "South Africa": "za.svg",
    "South Korea": "kr.svg",
    "Spain": "es.svg",
    "Sweden": "se.svg",
    "Switzerland": "ch.svg",
    "Tunisia": "tn.svg",
    "Turkey": "tr.svg",
    "Ukraine": "ua.svg",
    "United States": "us.svg",
    "Uruguay": "uy.svg",
    "Venezuela": "ve.svg",
    "Wales": "gb-wls.svg",
    "Congo DR": "cd.svg",
    "Haiti": "ht.svg",
    "Uzbekistan": "uz.svg",
    "Cabo Verde": "cv.svg",
    "Curacao": "cw.svg",
    "Jordan": "jo.svg",
}
